name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - test
      - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_WORKSPACE: ${{ github.ref_name }}  # Branch name maps to workspace

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Select or create workspace
      - name: Select Terraform Workspace
        run: |
          terraform workspace select ${{ env.TF_WORKSPACE }} || terraform workspace new ${{ env.TF_WORKSPACE }}

      # Validate Terraform code
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Terraform Apply for Staging (manual approval)
      - name: Terraform Apply Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "Manual approval required for staging apply"
          terraform apply -auto-approve tfplan

      # Terraform Apply for Main / Prod (auto)
      - name: Terraform Apply Prod
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Applying Terraform plan for main branch (prod)..."
          terraform workspace select main || terraform workspace new main
          terraform apply -auto-approve tfplan
